#!/usr/bin/env python3
"""Render a mock configuration for this factory's build root.

Packit builds locally with `packit build in-mock`, which is `mock --root <cfg>
<srpm>` (packit/cli/builds/mock_build.py, packit/api.py run_mock_build).
build-stage.yml installs mock in every job and never invokes it: the build is
bare `rpmbuild` in a container that hand-simulates a build root, as the
build-failure-triage skill says outright. The consequences are real -- no clean
root per package, no reset between the packages of one matrix job, and anything
upstream documents as "mock sets this" is unset unless the workflow sets it by
hand, which is how `USER` was missed.

Using mock needs a config that carries the same build-root policy the container
assembles by hand: Fedora paired with Hummingbird, Hummingbird winning by
priority and by name, prior stages winning over both, and one superseded ruby
excluded from the repository that ships them. That policy is what this renders.

The container path in build-stage.yml keeps that policy inline, and this module
restates it, so tests/test_mock_config.py parses the workflow and fails if the
two ever disagree.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

# Hummingbird ships newer versions of these names than Fedora 44 does, and the
# two must never mix in one transaction: libicu 78.3 against 77.1 broke samba
# and evolution-data-server, Fedora ruby 3.3/3.4-default-gems against
# Hummingbird ruby4.0-default-gems broke webkitgtk, colord, libnotify and zsh,
# and sqlite 3.51.2 winning over 3.53.4 made subversion unable to open a
# repository at all.
HUMMINGBIRD_WINS = (
    "ruby-default-gems",
    "ruby3.3-default-gems",
    "ruby3.4-default-gems",
    "libicu",
    "icu",
    "gpgme",
    "qt6-qtbase",
    "sqlite",
    "sqlite-libs",
)

# Hummingbird ships ruby3.3-, ruby3.4- and ruby4.0-default-gems, and all three
# claim the same files, so the root resolves and then dies in rpm on
# /usr/bin/erb (issue #75). Exclude the legacy pair from the Hummingbird
# repository, where they are the only providers, so ruby4.0 alone answers.
HUMMINGBIRD_REPO_EXCLUDE = (
    "ruby3.3-default-gems",
    "ruby3.4-default-gems",
    # libicu-77.*-*hum1 does NOT belong here, though it was added once and had
    # to come back out. Hummingbird has migrated to ICU 78 and only its
    # superseded builds link .so.77, so excluding 77 looked free. But the build
    # root also carries Fedora binaries Hummingbird never rebuilt, and
    # libical-3.0.20-7.fc44 requires libicuuc.so.77 outright. Fedora libicu is
    # already excluded above, so Hummingbird superseded 77 is the last provider
    # of .so.77; excluding it too left none and bluez stopped resolving at stage
    # 0 of run 35443117478. See the matching note in build-stage.yml.
)

FEDORA_RELEASEVER = "44"

TEMPLATE = """# Generated by tools/mock_config.py -- do not edit manually.
#
# The build root this factory needs: Fedora {releasever} paired with
# Hummingbird, mirroring how Hummingbird pairs them in images/variables.yml.
# Fedora is only the other half of the buildroot, the way a compiler is; the
# packages built here are for Hummingbird and installed on Hummingbird.
config_opts['root'] = '{root_name}'
config_opts['target_arch'] = 'x86_64'
config_opts['legal_host_arches'] = ('x86_64',)
config_opts['chroot_setup_cmd'] = 'install @buildsys-build'
config_opts['releasever'] = '{releasever}'
config_opts['package_manager'] = 'dnf5'
config_opts['extra_chroot_dirs'] = ['/run/lock']
# rand_core ships its crate docs as %doc and its lib.rs does
# #![doc = include_str!("../README.md")], so a root that drops documentation
# cannot build rust-just. Mock keeps docs by default; this says so out loud
# because the container path had to restore it.
config_opts['nosync'] = False

config_opts['dnf.conf'] = \"\"\"
[main]
keepcache=1
debuglevel=2
reposdir=/dev/null
logfile=/var/log/yum.log
retries=20
obsoletes=1
gpgcheck=0
assumeyes=1
install_weak_deps=0
metadata_expire=0
# Not best=1, although Hummingbird's own mock.cfg sets it. Its repository
# is internally consistent; this root mixes it with Fedora and with a
# Hummingbird that carries superseded builds -- python3-gpg exists only at
# gpgme 2.0.1-3.1 while gpgme-devel is at 2.0.1-6 -- and best=1 refuses the
# older consistent set: samba's hermetic lock failed on exactly that in run
# 36207220192. The container lane, which built every published package,
# resolves with dnf's default, best=0; the hermetic lane now matches it.
best=0
protected_packages=
module_platform_id=platform:f{releasever}
user_agent=utah-packages-mock/1

[fedora]
name=fedora
metalink=https://mirrors.fedoraproject.org/metalink?repo=fedora-{releasever}&arch=x86_64
gpgcheck=0
skip_if_unavailable=False
excludepkgs={fedora_excludes}

[updates]
name=updates
metalink=https://mirrors.fedoraproject.org/metalink?repo=updates-released-f{releasever}&arch=x86_64
gpgcheck=0
skip_if_unavailable=False
excludepkgs={fedora_excludes}

[public-hummingbird-x86_64-rpms]
name=public-hummingbird-x86_64-rpms
baseurl=https://packages.redhat.com/api/pulp-content/public-hummingbird/x86_64/
enabled=1
sslverify=1
gpgcheck=0
priority=10
zchunk=false
excludepkgs={hummingbird_repo_excludes}
{extra_repos}\"\"\"
"""

STAGES_REPO = """
[stages]
name=stages
baseurl=file://{path}
enabled=1
gpgcheck=0
priority=1
"""

FACTORY_REPO = """
[factory]
name=factory
baseurl={url}
enabled=1
gpgcheck=0
priority=5
"""


# What a hermetic build needs on top (tools/hermetic_build.sh): mock takes
# its bootstrap tooling from a container image instead of from the network,
# and only an image already carrying dnf5 ("ready") can be replayed offline
# from the lockfile. The image is the factory's own pinned build root
# (config/buildroot-image), so the bootstrap is the same bytes every job
# already builds with.
HERMETIC = """
config_opts['use_bootstrap_image'] = True
config_opts['bootstrap_image'] = '{bootstrap_image}'
config_opts['bootstrap_image_ready'] = True
"""


def render(
    *,
    root_name: str = "utah-hummingbird-x86_64",
    factory_repo: str = "",
    stages_dir: str = "",
    prior_built: tuple[str, ...] = (),
    bootstrap_image: str = "",
    hummingbird_extra_excludes: tuple[str, ...] = (),
) -> str:
    """The mock config for one build.

    Args:
        factory_repo: The published repository, so a package skipped as already
            built is reachable. Omitted when there is none, in which case
            nothing may be skipped -- see tools/rebuild_plan.py.
        stages_dir: A local repository of RPMs earlier stages produced.
        prior_built: Names those earlier stages built. Priority alone does not
            keep Fedora out: gnome-control-center pulled Fedora
            accountsservice 23.13.9 over a stage-0 26.27.3 because the Fedora
            main package pinned accountsservice-libs to its own exact NEVR.
            Whatever an earlier stage built, Fedora must not answer for.
    """
    fedora_excludes = ",".join((*HUMMINGBIRD_WINS, *prior_built))
    extra = ""
    if stages_dir:
        extra += STAGES_REPO.format(path=stages_dir)
    if factory_repo:
        extra += FACTORY_REPO.format(url=factory_repo)
    rendered = TEMPLATE.format(
        root_name=root_name,
        releasever=FEDORA_RELEASEVER,
        hummingbird_repo_excludes=",".join(
            (*HUMMINGBIRD_REPO_EXCLUDE, *hummingbird_extra_excludes)
        ),
        fedora_excludes=fedora_excludes,
        extra_repos=extra,
    )
    if bootstrap_image:
        rendered += HERMETIC.format(bootstrap_image=bootstrap_image)
    return rendered


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--factory-repo", default="")
    parser.add_argument("--stages-dir", default="")
    parser.add_argument(
        "--prior-built",
        default="",
        help="Comma-separated names earlier stages built, excluded from Fedora",
    )
    parser.add_argument("--root-name", default="utah-hummingbird-x86_64")
    parser.add_argument(
        "--bootstrap-image",
        default="",
        help="Bootstrap mock from this ready image (hermetic builds)",
    )
    parser.add_argument(
        "--hummingbird-exclude",
        default="",
        help="Comma-separated extra excludepkgs for the Hummingbird repository",
    )
    args = parser.parse_args()

    prior = tuple(name for name in args.prior_built.split(",") if name)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(
        render(
            root_name=args.root_name,
            factory_repo=args.factory_repo,
            stages_dir=args.stages_dir,
            prior_built=prior,
            bootstrap_image=args.bootstrap_image,
            hummingbird_extra_excludes=tuple(
                name for name in args.hummingbird_exclude.split(",") if name
            ),
        )
    )
    print(
        json.dumps(
            {
                "config": str(args.output),
                "root": args.root_name,
                "factory_repo": bool(args.factory_repo),
                "stages": bool(args.stages_dir),
                "prior_built": len(prior),
            },
            sort_keys=True,
        )
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
